# Generated by Django 3.1.3 on 2020-11-21 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReportApp', '0002_testcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='method_name',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
