# Generated by Django 3.1.3 on 2020-11-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportApp', '0004_newtestcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='project',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='description',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='status',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='title',
        ),
        migrations.AddField(
            model_name='testcase',
            name='data',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='NewTestCase',
        ),
    ]
