# Generated by Django 3.1.3 on 2020-11-24 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReportApp', '0005_auto_20201122_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('method_name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('severity', models.CharField(blank=True, max_length=20)),
                ('duration', models.TimeField()),
                ('parameters', models.CharField(blank=True, max_length=200)),
                ('steps', models.TextField(blank=True, max_length=2000)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='ReportApp.run')),
            ],
        ),
        migrations.DeleteModel(
            name='TestCase',
        ),
    ]
