# Generated by Django 3.1.3 on 2020-12-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportApp', '0007_auto_20201124_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='attachment',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='duration',
            field=models.TimeField(blank=True),
        ),
    ]
