# Generated by Django 3.1.3 on 2020-12-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportApp', '0008_auto_20201201_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
