# Generated by Django 3.1.3 on 2020-12-01 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReportApp', '0009_auto_20201201_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='duration',
        ),
    ]
