# Generated by Django 3.1.3 on 2020-12-01 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReportApp', '0010_remove_testresult_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='attachment',
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ReportApp.testresult')),
            ],
        ),
    ]
