# Generated by Django 3.1.3 on 2020-12-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReportApp', '0011_auto_20201201_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='project',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ReportApp.project'),
            preserve_default=False,
        ),
    ]
