# Generated by Django 3.1.3 on 2020-12-01 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReportApp', '0013_remove_run_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='project',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ReportApp.project'),
            preserve_default=False,
        ),
    ]
