# Generated by Django 3.1.3 on 2020-12-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportApp', '0014_run_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='history_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='labels',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='testresult',
            name='start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='stop',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='test_case_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='parameters',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='severity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='steps',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
